### PR TITLE
Patience

### PR DESCRIPTION
**Pull request by PeshO2K**
file_storage.py:
Added and all classes method that returns a dictionary of the parent class and all direct child classes.
console.py:
Rewrote the error_handler, added helper functions for casting attributes, mapping methods, updated the fetch class using the newly created all_classes method

### CODE REVIEW

**Comment by bravemaster3** [comment]
I have been testing your current changes this morning from your local branch, and so far I noticed a couple of problems:

1. <Class_name>.all()

Should display a bit differently from all <Class_name>

The first case should not show the elements in quotes.
The second should. That is why I implemented before a print vs. return logic, to fetch the one with quotes, and print it differently for <Class_name>.all()

2. The current matching of regex.. in the default method matches anything in the form x.y()

Therefore, it doesn't go to the default to raise a cmd_not_found type of error.  for example, literally x.y() goes silent because it is not handled in.

But I guess this can be fixed easily by adding a ".*" At the end of the regex expression.

3. Related to the previous point, if you have a correct command of type x.y() followed by another text, it treats the whole thing as one command and hence says no command found, but our current logic is that it should ignore the additional arguments.

In addition, default method might be better when not too general. For instance at the moment, we were not asked to handle User.create(), but it works because it runs do_create() with the current structure of the default function.

**Comment by bravemaster3** [comment]
One more thing. Just a thought, since we don't know how storage will develop as it will be connected to database management... I was wondering if it is not better to actually move the all_classes method to BaseModel instead. We can make it a static class method there.

**Comment by PeshO2K** [comment]
> One more thing. Just a thought, since we don't know how storage will develop as it will be connected to database management... I was wondering if it is not better to actually move the all_classes method to BaseModel instead. We can make it a static class method there.

I do not agree, having it in storage allows us to use it dynamically and not limit it to a single base class.

**Comment by bravemaster3** [comment]
Sure! As you prefer. But that is why I said static class method. It is in the class, but you don't need an instance of the class to use it. That is what static methods are for.
You can see that that method doesn't depend on the class itself. It only works on the argument it was given.

**Comment by bravemaster3** [comment]
> > One more thing. Just a thought, since we don't know how storage will develop as it will be connected to database management... I was wondering if it is not better to actually move the all_classes method to BaseModel instead. We can make it a static class method there.
> 
> I do not agree, having it in storage allows us to use it dynamically and not limit it to a single base class.

Sure! As you prefer. But that is why I said static class method. It is in the class, but you don't need an instance of the class to use it. That is what static methods are for.
You can see that that method doesn't depend on the class itself. It only works on the argument it was given.

**Comment by PeshO2K** [comment]
> > > One more thing. Just a thought, since we don't know how storage will develop as it will be connected to database management... I was wondering if it is not better to actually move the all_classes method to BaseModel instead. We can make it a static class method there.
> > 
> > 
> > I do not agree, having it in storage allows us to use it dynamically and not limit it to a single base class.
> 
> Sure! As you prefer. But that is why I said static class method. It is in the class, but you don't need an instance of the class to use it. That is what static methods are for. You can see that that method doesn't depend on the class itself. It only works on the argument it was given.

:D I guess I previously missed the point. I agree to making it a static method.

**Pull request merged**
